language: ruby
cache: bundler
rvm:
  - 2.5
  - 2.6
gemfile:
  - gemfiles/puppet3.gemfile
  - gemfiles/puppet4.gemfile
script:
  - "bundle exec rake validate"
  - "bundle exec rake lint"
  - "bundle exec rake spec"
